# Generated by Django 5.1.7 on 2025-04-14 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_authtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthToken',
        ),
    ]
