# Generated by Django 5.1.7 on 2025-04-28 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_address_file_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='type',
        ),
    ]
