# Generated by Django 5.1.7 on 2025-04-28 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_phonenumber_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='is_primary',
        ),
    ]
